FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

ARG REACT_APP_SERVER_PROTOCOL=https
ARG REACT_APP_SERVER_IP=api.vibivibi.site

# ARG REACT_APP_SERVER_PROTOCOL=http
# ARG REACT_APP_SERVER_IP=localhost:8443

RUN REACT_APP_SERVER_PROTOCOL=$REACT_APP_SERVER_PROTOCOL \
    REACT_APP_SERVER_IP=$REACT_APP_SERVER_IP \
    npm run build

RUN npm install -g serve

CMD ["serve", "-s", "build"]

EXPOSE 3000